name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- [#$NUMBER] $TITLE - Thanks to @$AUTHOR!"
exclude-labels:
  - automated
categories:
  - title: "🔒 Security"
    labels:
      - "security"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "📄 Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "🔗 Dependencies"
    labels:
      - "dependencies"
  - title: "🌀 Meta"
    labels:
      - "meta"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
