using System.Text.Json.Serialization;
using PinguApps.Appwrite.Shared.Requests.Account.Validators;
using PinguApps.Appwrite.Shared.Utils;

namespace PinguApps.Appwrite.Shared.Requests.Account;

/// <summary>
/// The request for creating a session
/// </summary>
public class CreateSessionRequest : BaseRequest<CreateSessionRequest, CreateSessionRequestValidator>
{
    /// <summary>
    /// User ID. Choose a custom ID or generate a random ID with <see cref="IdUtils.GenerateUniqueId(int)"/>. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char. Max length is 36 chars
    /// </summary>
    [JsonPropertyName("userId")]
    public string UserId { get; set; } = IdUtils.GenerateUniqueId();

    /// <summary>
    /// Secret of a token generated by login methods. For example, the CreateMagicURLToken or CreatePhoneToken methods.
    /// </summary>
    [JsonPropertyName("secret")]
    public string Secret { get; set; } = string.Empty;
}
