name: Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CLIENT_PROJECT_NAME: PinguApps.Appwrite.Client
  SERVER_PROJECT_NAME: PinguApps.Appwrite.Server
  REALTIME_PROJECT_NAME: PinguApps.Appwrite.Realtime
  DOTNET_VERSION: '8.0'

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    permissions:
      pull-requests: write
      contents: read
      issues: read
      checks: write
