name: PR

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    permissions:
      pull-requests: write
      contents: read
      issues: read
      checks: write

  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.10
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-4o'
          GITHUB_TOKEN: ${{ github.token }}
