name: 'Stale issues & PRs'
on:
  schedule:
    - cron: '27 0,12 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9
        with:
          days-before-stale: 7
          days-before-pr-stale: 2
          days-before-close: 3
          stale-issue-message: 'This issue has been marked as stale, and will be automatically closed in 3 days.'
          stale-pr-message: 'This PR has been marked as stale, and will be automatically closed in 3 days.'
          close-issue-message: 'Closing issue as it has been marked as stale for 3 days.'
          close-pr-message: 'Closing PR as it has been marked as stale for 3 days.'
          exempt-all-milestones: true
          exempt-pr-labels: 'dependencies'
